name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set up go
          uses: actions/setup-go@v4
          with: 
              go-version: "1.21"
              cache-dependency-path: bugtracker-backend/go.sum

        - name: Execute backend unit tests
          working-directory: ./bugtracker-backend
          run: |
            go test -v ./...

  unit-tests-frontend:
     needs: unit-tests-backend
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v4

        - name: set up Node.js
          uses: actions/setup-node@v4
          with: 
            node-version: "20"
            cache-dependency-path: bugtracker-frontend/package-lock.json

        - name: Execute frontend unit tests
          working-directory: ./bugtracker-frontend 
          run: |
            npm ci
            npm test

        - name: Publish frontend test results
          uses: dorny/test-reporter@v1
          if: always()
          with: 
              name: frontend unit test report
              path: bugtracker-frontend/test-results.xml
              reporter: jest-junit